cp storage/downloads/dex-dev/start-lxde.sh .shortcuts
cp storage/downloads/dex-dev/start-lxqt.sh .shortcuts
cp storage/downloads/dex-dev/start-xfce.sh .shortcuts
cp storage/downloads/dex-dev/audio-tcp.sh .
cp storage/downloads/dex-dev/dev.sh .
cp storage/downloads/dex-dev/admin-lxde.sh .shortcuts
cp storage/downloads/dex-dev/admin-lxqt.sh .shortcuts
cp storage/downloads/dex-dev/admin-xfce.sh .shortcuts
cp storage/downloads/dexmode/end.sh .
cp storage/downloads/dexmode/end.sh .shortcuts